config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  resources :doctors
  resources :patients
  devise_for :users

  get '/'  => 'users#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
    belongs_to :doctor
    belongs_to :patient
end

app/models/doctor.rb
class Doctor < ApplicationRecord
    # belongs_to :user
    has_many :appointments
    has_many :patients, :through => :appointments
end

app/models/patient.rb
class Patient < ApplicationRecord
    has_many :appointments
    has_many :doctors, :through => :appointments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]

  # GET /appointments
  def index
    @appointments = Appointment.all
    @doctors = Doctor.all
    @patients = Patient.all
  end

  # GET /appointments/1
  def show
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments
  def create
    @appointment = Appointment.new(appointment_params)
      if @appointment.save
        ModelMailer.create_appointment(@message).deliver
        redirect_to @appointment, notice: 'Appointment made.' 
      else
        render :new 
      end
  end

  # PATCH/PUT /appointments/1
  def update
      if @appointment.update(appointment_params)
        redirect_to @appointment, notice: 'Appointment changed.' 
 
      else
        render :edit
      end
  end

  # DELETE /appointments/1
  def destroy
    @appointment.destroy
      redirect_to appointments_url, notice: 'Appointment cancelled.'
  end

  private
    # # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appointment_params
      params.require(:appointment).permit(:patient_id, :doctor_id, :appt, :details)
    end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show, :edit, :update, :destroy]

  # GET /doctors
  def index
    @doctors = Doctor.all
  end

  # GET /doctors/1
  def show
  end

  # GET /doctors/new
  def new
    @doctor = Doctor.new
  end

  # GET /doctors/1/edit
  def edit
  end

  # POST /doctors
  def create
    @doctor = Doctor.new(doctor_params)
      if @doctor.save
        redirect_to @doctor, notice: 'Doctor was entered.' 
      else
        render :new
      end
  end

  # PATCH/PUT /doctors/1
  def update
      if @doctor.update(doctor_params)
        redirect_to @doctor, notice: 'Doctor was updated.'
      else
        render :edit 
      end
  end

  # DELETE /doctors/1
  def destroy
    @doctor.destroy
    redirect_to doctors_url, notice: 'Doctor was deleted.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doctor
      @doctor = Doctor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doctor_params
      params.require(:doctor).permit(:last_name, :first_name, :speciality, :description, :interests, :contact_number, :email)
    end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  # GET /patients
  def index
    @patients = Patient.all
  end

  # GET /patients/1
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  def create
    @patient = Patient.new(patient_params)
      if @patient.save
        redirect_to @patient, notice: 'Patient was entered.' 
      else
        render :new 
      end
  end

  # PATCH/PUT /patients/1
  def update
      if @patient.update(patient_params)
        redirect_to @patient, notice: 'Patient was updated.'

      else
        render :edit 
      end
  end

  # DELETE /patients/1
  def destroy
    @patient.destroy
      redirect_to patients_url, notice: 'Patient was deleted.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:last_name, :first_name, :birthdate, :phone, :email, :misc)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def index
        @user = User.all
        @current_user = current_user
    end

    
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/appointments/_form.html.erb
<%= form_with(model: appointment, local: true) do |form| %>
  <% if appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
      <% appointment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="appointment_form">
  <div class="field">
    <%= form.label :patient_id %>
    <%= form.collection_select(:patient_id, Patient.all, :id, :last_name, {}) %><br/>
  </div>

  <div class="field">
    <%= form.label :doctor_id %>
    <%= form.collection_select(:doctor_id, Doctor.all, :id, :last_name, {}) %><br/>
  </div>

  <div class="field">
    <%= form.label :appt %><br/>
    <%= form.text_field :appt, {placeholder: 'Select Date', :class => "datepicker"} %>
    <%= form.text_field :appt, {placeholder: 'Select Time', :class => "timepicker"}%>
  </div>

  <div class="field">
    <%= form.label :details %>
    <span> (ICD-9 Code)</span>
    <%= form.number_field :details %>

   
  </div><br/>

  <div class="actions">
    <%= form.submit %>
  </div><br/>

     

</div>  
<% end %>

<button id="symp">Code Look Up</button>

<div id="playground"></div>

<h4>Quick guide to ICD-9 codes</h4>
<table class="striped">
<tr><td>001–139</td><td>vinfectious and parasitic diseases</td></tr>
<tr><td>140–239</td><td>neoplasms</td></tr>
<tr><td>240–279</td><td>endocrine, nutritional and metabolic diseases, and immunity disorders</td></tr>
<tr><td>280–289</td><td>diseases of the blood and blood-forming organs</td></tr>
<tr><td>290–319</td><td>mental disorders</td></tr>
<tr><td>320–389</td><td>diseases of the nervous system and sense organs</td></tr>
<tr><td>390–459</td><td>diseases of the circulatory system</td></tr>
<tr><td>460–519</td><td>diseases of the respiratory system</td></tr>
<tr><td>520–579</td><td>diseases of the digestive system</td></tr>
<tr><td>580–629</td><td>diseases of the genitourinary system</td></tr>
<tr><td>630–679</td><td>complications of pregnancy, childbirth, and the puerperium</td></tr>
<tr><td>680–709</td><td>diseases of the skin and subcutaneous tissue</td></tr>
<tr><td>710–739</td><td>diseases of the musculoskeletal system and connective tissue</td></tr>
<tr><td>740–759</td><td>congenital anomalies</td></tr>
<tr><td>760–779</td><td>certain conditions originating in the perinatal period</td></tr>
<tr><td>780–799</td><td>symptoms, signs, and ill-defined conditions</td></tr>
<tr><td>800–999</td><td>injury and poisoning</td></tr>
</table>


<script>

    document.querySelector('#symp').addEventListener('click', function (e) {

        let searchTerm = document.querySelector("#appointment_details").value;
        //let searchTerm = "Diabetes%20mellitus%20with%20other%20coma%20type%201%20uncontrolled"
        let lang = "en";
        
        fetch("https://connect.medlineplus.gov/service?mainSearchCriteria.v.c="+searchTerm+"&knowledgeResponseType=application/json&informationRecipient.languageCode.c="+lang)
        .then( function(response){
            return response.json();
        }).then(function(data){
            
            let parsedData = JSON.parse(JSON.stringify(data));
            console.log(parsedData.feed)

            let pg = document.querySelector("#playground");

            pg.innerHTML = "";
            for(let i = 0; i<parsedData.feed.entry.length;i++){
              pg.innerHTML += "<div><h3>"+parsedData.feed.entry[i].title._value+"</h3>";
              pg.innerHTML += parsedData.feed.entry[i].summary._value+"</p>"
            }
            pg.innerHTML += "<div>Data source from: <br>";
            //pg.innerHTML = "<a href='"+parsedData.feed.author.url._value+"'>"
            pg.innerHTML += parsedData.feed.author.name._value
            pg.innerHTML += "</div><br><br>";

            }) 
    })

   
</script>

app/views/appointments/edit.html.erb
<h1>Edit Appointment</h1>

<%= render 'form', appointment: @appointment %>

<%= link_to 'Show', @appointment %> |
<td><%= link_to 'X', @appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td> |
      
<%= link_to 'List of appointments', appointments_path %>

app/views/appointments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Appointments</h1>

<table>
  <thead>
    <tr>
      <th>Patient</th>
      <th>Doctor</th>
      <th>Appt</th>
  
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
      
        <td><%= appointment.patient.first_name%> <%=appointment.patient.last_name%></td>
        <td>Dr. <%= appointment.doctor.last_name %></td>
        <td><%= appointment.appt.strftime("%m/%d/%Y %I:%M%p") %></td>
        <td><%= link_to 'Details', appointment %></td>
        <td><%= link_to 'Edit', edit_appointment_path(appointment) %></td>
        </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Appointment', new_appointment_path %>

app/views/appointments/new.html.erb
<h1>New Appointment</h1>

<%= render 'form', appointment: @appointment %>

<%= link_to 'List of Appointments', appointments_path %>

<div class="list">

app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Patient:</strong>
  <%= @appointment.patient.first_name %>
  <%= @appointment.patient.last_name %>
</p>

<p>
  <strong>Doctor:</strong>
 Mr. <%= @appointment.doctor.last_name %>
</p>

<p>
  <strong>Appt:</strong>
  <%= @appointment.appt %>
</p>

<p>
  <strong>Details:</strong>
  <span id="code"><%= @appointment.details %></span>
  <button id="lookup">Details</button>
</p>

<%= link_to 'Edit', edit_appointment_path(@appointment) %> |
<%= link_to 'Return to Appointment List', appointments_path %>

<div id="playground"></div>




<script>
document.querySelector('#lookup').addEventListener('click', function(e){
             let searchTerm = document.querySelector("#code").textContent;
        console.log(searchTerm)
        //let searchTerm = "Diabetes%20mellitus%20with%20other%20coma%20type%201%20uncontrolled"
        let lang = "en";
        
        fetch("https://connect.medlineplus.gov/service?mainSearchCriteria.v.c="+searchTerm+"&knowledgeResponseType=application/json&informationRecipient.languageCode.c="+lang)
        .then( function(response){
            return response.json();
        }).then(function(data){
            
            let parsedData = JSON.parse(JSON.stringify(data));
            console.log(parsedData.feed)

            let playground = document.querySelector("#playground");
            playground.innerHTML = "<div>";
            //playground.innerHTML = "<a href='"+parsedData.feed.author.url._value+"'>"
            playground.innerHTML += parsedData.feed.author.name._value
            playground.innerHTML += "</div>";
            for(let i = 0; i<parsedData.feed.entry.length;i++){
              playground.innerHTML += "<div><h3>"+parsedData.feed.entry[i].title._value+"</h3>";
              playground.innerHTML += parsedData.feed.entry[i].summary._value+"</p>"
            }
      

            }) 
})


window.addEventListener("load", function (e) {

        let searchTerm = document.querySelector("#code").textContent;
        console.log(searchTerm)
        //let searchTerm = "Diabetes%20mellitus%20with%20other%20coma%20type%201%20uncontrolled"
        let lang = "en";
        
        fetch("https://connect.medlineplus.gov/service?mainSearchCriteria.v.c="+searchTerm+"&knowledgeResponseType=application/json&informationRecipient.languageCode.c="+lang)
        .then( function(response){
            return response.json();
        }).then(function(data){
            
            let parsedData = JSON.parse(JSON.stringify(data));
            console.log(parsedData.feed)

            let playground = document.querySelector("#playground");
            playground.innerHTML = "<div>";
            //playground.innerHTML = "<a href='"+parsedData.feed.author.url._value+"'>"
            playground.innerHTML += parsedData.feed.author.name._value
            playground.innerHTML += "</div>";
            for(let i = 0; i<parsedData.feed.entry.length;i++){
              playground.innerHTML += "<div><h3>"+parsedData.feed.entry[i].title._value+"</h3>";
              playground.innerHTML += parsedData.feed.entry[i].summary._value+"</p>"
            }
      

            }) 
    })

   
</script>

app/views/doctors/_form.html.erb
<%= form_with(model: doctor, local: true) do |form| %>
  <% if doctor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(doctor.errors.count, "error") %> prohibited this doctor from being saved:</h2>

      <ul>
      <% doctor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :speciality %>
    <%= form.text_field :speciality %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :interests %>
    <%= form.text_field :interests %>
  </div>

  <div class="field">
    <%= form.label :contact_number %>
    <%= form.text_field :contact_number %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/doctors/edit.html.erb
<h1>Edit Doctor Information</h1>

<%= render 'form', doctor: @doctor %>

<%= link_to 'Show', @doctor %> |
<%= link_to 'Delete', @doctor, method: :delete, data: { confirm: 'Are you sure?' } %> | 
<%= link_to 'Back', doctors_path %>
      

app/views/doctors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Doctors</h1>

<table>
  <thead>
    <tr>
      <th>Last name</th>
      <th>First name</th>
      <th>Speciality</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @doctors.each do |doctor| %>
      <tr>
        <td><%= doctor.last_name %></td>
        <td><%= doctor.first_name %></td>
        <td><%= doctor.speciality %></td>

        <td><%= link_to 'Details', doctor %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Doctor', new_doctor_path %>

app/views/doctors/new.html.erb
<h1>New Doctor</h1>

<%= render 'form', doctor: @doctor %>

<%= link_to 'Back', doctors_path %>

app/views/doctors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Last name:</strong>
  <%= @doctor.last_name %>
</p>

<p>
  <strong>First name:</strong>
  <%= @doctor.first_name %>
</p>

<p>
  <strong>Speciality:</strong>
  <%= @doctor.speciality %>
</p>

<p>
  <strong>Description:</strong>
  <%= @doctor.description %>
</p>

<p>
  <strong>Interests:</strong>
  <%= @doctor.interests %>
</p>

<p>
  <strong>Contact number:</strong>
  <%= @doctor.contact_number %>
</p>

<p>
  <strong>Email:</strong>
  <%= @doctor.email %>
</p>

<%= link_to 'Edit', edit_doctor_path(@doctor) %> |
<%= link_to 'Delete', @doctor, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'List all Docs', doctors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DocAppointmentbook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"> 
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/js/materialize.min.js"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
    <div class="nav-wrapper">
      <a href="#" class="brand-logo">Health-Tracker</a>
      <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <% if !current_user %>
        <li><%= link_to "Sign In", new_user_session_path,  :"data-turbolinks" => false  %></li>
        <li><%= link_to "Sign Up", new_user_registration_path,  :"data-turbolinks" => false  %></li>
        <% else %>
        <li><%= link_to "My Account", user_session_path,  :"data-turbolinks" => false %></li>
        <li><%= link_to "Patients", patients_path,  :"data-turbolinks" => false %></li>
        <li><%= link_to "Doctors", doctors_path,  :"data-turbolinks" => false %></li>
        <li><%= link_to "Appointments", appointments_path,  :"data-turbolinks" => false %></li>
        <li><a href="#terms" class="modal-trigger">&#128214;</a></li>
        <li><%= link_to "Sign Out", destroy_user_session_path,  :"data-turbolinks" => false, method: :delete %>
        <% end %>
      </ul>
      <ul class="sidenav" id="mobile-demo">
        <% if !current_user %>
        <li><%= link_to "Sign In", new_user_session_path, :"data-turbolinks" => false %></li>
        <li><%= link_to "Sign Up", new_user_registration_path, :"data-turbolinks" => false %></li>
        <% else %>
        <li><%= link_to "My Account", user_session_path, :"data-turbolinks" => false %></li>
       
        <li><%= link_to "Patients", patients_path, :"data-turbolinks" => false %></li>
        <li><%= link_to "Doctors", doctors_path, :"data-turbolinks" => false %></li>
        <li><%= link_to "Appointments", appointments_path, :"data-turbolinks" => false %></li>
        <li><a href="#terms" class="modal-trigger">&#128214; Dictonary</a></li>
        <li><%= link_to "Sign Out", destroy_user_session_path, :"data-turbolinks" => false, method: :delete %>
        <% end %>
       </ul>
    </div>
  </nav>
  <div class="container">
    <%= yield %>
    <div class="modal" id="terms">
      <div class="container" style="padding: 20px;">
        <label for="search"></label>
        <input type='text' id="search-text" name="search">
        <input type="button" class="waves-effect waves-light btn-small" id="search" value="search">
        <input type="button" class="waves-effect waves-light btn-small" id="list" value="list all terms">
        <div id="placer"></div>
      </div>
    </div>
  </div>
  </body>
</html>

app/views/patients/_form.html.erb
<%= form_with(model: patient, local: true) do |form| %>
  <% if patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% patient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="patients_form">
  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :birthdate %>
    <%= form.date_select :birthdate, :start_year => 1930, :end_year => 2012 %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field number_to_phone(:phone) %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :misc %>
    <%= form.text_area :misc %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
</div>
<% end %>

app/views/patients/edit.html.erb
<h1>Edit Patient Information</h1>

<%= render 'form', patient: @patient %>

<%= link_to 'Show', @patient %> |
<%= link_to 'Delete', @patient, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'List of Patients', patients_path %>

app/views/patients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Patients</h1>

<table>
  <thead>
    <tr>
      <th>Last name</th>
      <th>First name</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.last_name %></td>
        <td><%= patient.first_name %></td>
        <td><%= number_to_phone(patient.phone) %></td>
        <td><%= link_to 'Details', patient %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Patient', new_patient_path %>

app/views/patients/new.html.erb
<h1>New Patient</h1>

<%= render 'form', patient: @patient %>

<%= link_to 'Back', patients_path %>

app/views/patients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Last name:</strong>
  <%= @patient.last_name %>
</p>

<p>
  <strong>First name:</strong>
  <%= @patient.first_name %>
</p>

<p>
  <strong>Birthdate:</strong>
  <%= @patient.birthdate %>
</p>

<p>
  <strong>Phone:</strong>
  <%= number_to_phone(@patient.phone) %>
</p>

<p>
  <strong>Email:</strong>
  <%= @patient.email %>
</p>

<p>
  <strong>Misc:</strong>
  <%= @patient.misc %>
</p>

<%= link_to 'Edit', edit_patient_path(@patient) %> |
<%= link_to 'Delete', @patient, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'List of Patients', patients_path %>

app/views/users/index.html.erb
<% if current_user %>
<h3>Welcome <%= current_user.email %></h3>
<div style="display:flex; justify-content:space-around">
 <div><%= link_to "Edit Account", edit_user_registration_path %></div>
 <div><a href="#terms" class="modal-trigger">&#128214; Look it up</a></div>
</div>
<div class="log-photo">
 <%= image_tag("greet.jpg", alt: "greetings") %>
</div>

<% else %>


<div class="carousel">
    <div class="carousel-item"><%= image_tag("doctors_know.jpg") %></div>
    <div class="carousel-item"><%= image_tag("medimage1.jpeg") %></div>
    <div class="carousel-item"><%= image_tag("carouselimage3.jpg") %></div>
    <div class="carousel-item"><%= image_tag("carouselimage2.jpg") %></div>
    
  </div>

<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>